### PR TITLE
Preset Clearance Message

### PR DESCRIPTION
**Pull request by Tonewall**
Hey Sam, I created the function for preset clearance message option which can also be edited and fixed an issue in editing old message. The preset clearance message option shows up in the FlightsDetailsInfo.vue file. I can also make it show up in FlightsTable.vue file as well if you'd like, but I just thought it was only needed for new flights.
The only thing is that I couldn't actually save any of the clearances to see if they were saving correctly. Could you see if they function well?

### CODE REVIEW

**Comment by samcrane8** [comment]
Hmm can you explain a bit more on not being able to save the clearances? Are you logging in as the admin user?

**Comment by Tonewall** [comment]
Yeah I logged in as the admin/law*****
I can edit the clearance message from my localhost on the flightsdetails page, but when I press "save clearance" and reload the page, the old clearance message is still there instead of the edited version

**Comment by samcrane8** [comment]
Hmm can you open up your dev tools? See if the update_clearance post request is going through first. This is usually how I debug these things.

**Comment by Tonewall** [comment]
Yeah this is what I got when I clicked save:
Capture

**Comment by Tonewall** [comment]
Also, the save clearance button is disabled for me in the flightstable view

**Comment by Tonewall** [comment]
And I get these two errors but I haven't changed anything for commanderInfo
image

**Comment by Tonewall** [comment]
Yeah I get the same 400 bad request error in the production server in icarusmap.com with the same account

**Pull request closed without merging**
